server.address=0.0.0.0
server.port=8081


#######################################################################
# H2 console for PostgreSQL
# http://localhost:8080/h2-console
#######################################################################
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl=true

# you must use this to let the spring datasource to work
# http://5.9.10.113/67744719/spring-boot-data-jpa-with-h2-and-data-sql-table-not-found
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# Time zone to UTC
spring.datasource.url=jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS humanresources_schema\\;CREATE SCHEMA IF NOT EXISTS DBO\\;CREATE SCHEMA IF NOT EXISTS HR\\;CREATE SCHEMA IF NOT EXISTS PERSON\\;CREATE SCHEMA IF NOT EXISTS production\\;CREATE SCHEMA IF NOT EXISTS simulation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1



###################################################################
# redis springboot implementation
###################################################################
spring.data.redis.host=host.docker.internal
spring.data.redis.port=6379
#spring.redis.timeToLive=60 # in minutes -> is now implemented in ,configuration
spring.cache.typr=redis #spring will cache now with redis

# If a password is required:
# spring.data.redis.password=your-password


###################################################################
# Test redis client
###################################################################
#service.redis.cache.ttl=15
#service.redis.cache.url=redis://127.0.0.1:6379


